version: "3.7"
services:
  gservice:
    build: ./api
    environment:
      #edit these to point to the right Postgis DB
      - GSDB_DBNAME=gis
      - GSDB_HOSTNAME=db
      - GSDB_PORT=5432
      - GSDB_USER=jon
      - GSDB_PASS=jon
    ports:
     - "${PORT:-3000}:3000"

